### ISSUE TITLE
wrong number of arguments (4 for 0) only on Heroku

### ISSUE THREAD

**Issue by RalphAtHamburg** [stefanpenner/country_select#110]
= form_for @profile, :html => { :multipart => true } do |f|
        ...
        = t('.country')
        = f.country_select :country_code, priority_countries: ["DE", "FR", "GB", "US"]

This works perfect on my local environment but fails when I deploy it to heroku. There I get the following error message:

    User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    Started GET "/profiles/1-ralphathamburg/edit" for 79.228.15.18 at 2015-08-27 12:58:16 +0000
      Rendered profiles/_form.html.haml (7.3ms)
      Rendered profiles/edit.html.haml within layouts/application (9.4ms)
    
    Completed 500 Internal Server Error in 18ms (ActiveRecord: 3.0ms)
    ActionView::Template::Error (wrong number of arguments (4 for 0)):
        40:     %br/
        41:     
        42:     = t('.country')
    Processing by ProfilesController#edit as HTML
      Parameters: {"id"=>"1-ralphathamburg"}
        43:     = f.country_select :country_code, priority_countries: ["DE", "FR", "GB", "US"]
        44:     %br/
        45:     

Running with ruby '2.2.2' and 'rails', '4.2.3'

**Comment by scudco** [comment]
Which version of `country_select` are you using?

**Comment by scudco** [comment]
Here's an example app running on heroku:

https://country-select-test.herokuapp.com/

Source code is here:
https://github.com/scudco/country_select_test

**Comment by RalphAtHamburg** [comment]
I am using 2.3.0. It s also used by heroku. Strange, I can't see any differences between your example code and my code.

**Comment by scudco** [comment]
Can you post the full stack trace?

**Comment by RalphAtHamburg** [comment]
iMac:trisali ralph$ heroku logs
    2015-08-27T14:27:06.144443+00:00 app[web.1]: 	bin/rails:8:in `<main>'
    2015-08-27T14:27:06.144505+00:00 app[web.1]: [2015-08-27 14:27:06] INFO  going to shutdown ...
    2015-08-27T14:27:06.144572+00:00 app[web.1]: => Booting WEBrick
    2015-08-27T14:27:06.144539+00:00 app[web.1]: [2015-08-27 14:27:06] INFO  WEBrick::HTTPServer#start done.
    2015-08-27T14:27:06.144576+00:00 app[web.1]: => Run `rails server -h` for more startup options
    2015-08-27T14:27:06.144577+00:00 app[web.1]: => Ctrl-C to shutdown server
    2015-08-27T14:27:06.144574+00:00 app[web.1]: => Rails 4.2.3 application starting in production on http://0.0.0.0:14887
    2015-08-27T14:27:06.144579+00:00 app[web.1]: Exiting
    2015-08-27T14:27:07.661229+00:00 heroku[web.1]: Process exited with status 143
    2015-08-27T14:27:09.776669+00:00 heroku[worker.1]: Starting process with command `bundle exec rake jobs:work`
    2015-08-27T14:27:10.491952+00:00 heroku[worker.1]: State changed from starting to up
    2015-08-27T14:27:15.063171+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 22932 -e production`
    2015-08-27T14:27:18.136981+00:00 app[worker.1]: rake aborted!
    2015-08-27T14:27:18.137021+00:00 app[worker.1]: Don't know how to build task 'jobs:work'
    2015-08-27T14:27:18.137252+00:00 app[worker.1]: 
    2015-08-27T14:27:18.137255+00:00 app[worker.1]: (See full trace by running task with --trace)
    2015-08-27T14:27:19.181454+00:00 heroku[worker.1]: Process exited with status 1
    2015-08-27T14:27:19.182135+00:00 heroku[worker.1]: State changed from up to crashed
    2015-08-27T14:27:26.069487+00:00 heroku[web.1]: State changed from starting to up
    2015-08-27T14:27:25.996080+00:00 app[web.1]: [2015-08-27 14:27:25] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
    2015-08-27T14:27:25.996411+00:00 app[web.1]: [2015-08-27 14:27:25] INFO  WEBrick::HTTPServer#start: pid=3 port=22932
    2015-08-27T14:27:25.996057+00:00 app[web.1]: [2015-08-27 14:27:25] INFO  WEBrick 1.3.1
    2015-08-27T14:27:29.018506+00:00 app[web.1]: => Booting WEBrick
    2015-08-27T14:27:29.018514+00:00 app[web.1]: => Rails 4.2.3 application starting in production on http://0.0.0.0:22932
    2015-08-27T14:27:29.018515+00:00 app[web.1]: => Run `rails server -h` for more startup options
    2015-08-27T14:27:29.018518+00:00 app[web.1]: Started GET "/profiles/1-ralphathamburg" for 79.228.15.18 at 2015-08-27 14:27:29 +0000
    2015-08-27T14:27:29.018516+00:00 app[web.1]: => Ctrl-C to shutdown server
    2015-08-27T14:27:29.170951+00:00 app[web.1]: Processing by ProfilesController#show as HTML
    2015-08-27T14:27:29.261627+00:00 app[web.1]:   Profile Load (4.0ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:27:29.176767+00:00 app[web.1]:   Parameters: {"id"=>"1-ralphathamburg"}
    2015-08-27T14:27:29.319169+00:00 app[web.1]:   User Load (6.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:27:29.343792+00:00 app[web.1]:   ActsAsVotable::Vote Load (2.7ms)  SELECT "votes".* FROM "votes" WHERE "votes"."vote_flag" = $1 AND "votes"."voter_id" = $2 AND "votes"."voter_type" = $3  [["vote_flag", "t"], ["voter_id", 1], ["voter_type", "User"]]
    2015-08-27T14:27:29.579633+00:00 app[web.1]:   User Load (2.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    2015-08-27T14:27:30.406000+00:00 heroku[router]: at=info method=GET path="/profiles/1-ralphathamburg" host=trisali.herokuapp.com request_id=eefad9b1-ee02-40f4-8aa9-24caa826b616 fwd="79.228.15.18" dyno=web.1 connect=1ms service=1398ms status=200 bytes=4189
    2015-08-27T14:27:30.334849+00:00 app[web.1]:   Rendered experiences/_experience.html.haml (0.0ms)
    2015-08-27T14:27:30.342151+00:00 app[web.1]:   Rendered experiences/_experience.html.haml (0.0ms)
    2015-08-27T14:27:30.382200+00:00 app[web.1]:   Profile Load (3.7ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = $1 LIMIT 1  [["user_id", 1]]
    2015-08-27T14:27:30.404414+00:00 app[web.1]:   Rendered layouts/_footer.html.haml (19.6ms)
    2015-08-27T14:27:30.341777+00:00 app[web.1]:   Experience Load (1.6ms)  SELECT "experiences".* FROM "experiences" WHERE "experiences"."user_id" = $1  [["user_id", 1]]
    2015-08-27T14:27:30.342315+00:00 app[web.1]:   Rendered profiles/show.html.haml within layouts/application (973.3ms)
    2015-08-27T14:27:30.383925+00:00 app[web.1]:   Rendered layouts/_header.html.haml (27.8ms)
    2015-08-27T14:27:30.406702+00:00 app[web.1]: Completed 200 OK in 1228ms (Views: 1028.9ms | ActiveRecord: 63.5ms)
    2015-08-27T14:27:30.728243+00:00 heroku[router]: at=info method=GET path="/assets/application-134efb656780b360adf982093a49acc957f3e2e564783ce03e5c2d4954ef1c90.css" host=trisali.herokuapp.com request_id=f399c0a2-3678-4d35-b24b-53d7c32f898a fwd="79.228.15.18" dyno=web.1 connect=1ms service=19ms status=304 bytes=133
    2015-08-27T14:27:30.781952+00:00 heroku[router]: at=info method=GET path="/assets/vendor/modernizr-8560f87d0bc4f137917740acabfc72f0d469565340a978cb6aad12c44b48093a.js" host=trisali.herokuapp.com request_id=f36ad3a9-bd4c-415f-994f-c07c8b41d056 fwd="79.228.15.18" dyno=web.1 connect=1ms service=7ms status=304 bytes=133
    2015-08-27T14:27:30.856938+00:00 heroku[router]: at=info method=GET path="/assets/ubuntu-regular-ff6c85b5b809994e8f4a24027db9d6d64505001b0cb2fa7176ac3377e94a6e4f.ttf" host=trisali.herokuapp.com request_id=d6a10ad4-01ef-4077-8b91-d9c181748f3c fwd="79.228.15.18" dyno=web.1 connect=1ms service=14ms status=304 bytes=133
    2015-08-27T14:27:30.929326+00:00 heroku[router]: at=info method=GET path="/assets/beta_big-3edbf0ad36a647987edd88c9b2b9d81372b3e0ad82b865f06e31e6fd9dc8efb5.png" host=trisali.herokuapp.com request_id=8e6a306f-2835-4abb-8ff9-f0c2e7131249 fwd="79.228.15.18" dyno=web.1 connect=1ms service=8ms status=304 bytes=133
    2015-08-27T14:27:30.802562+00:00 heroku[router]: at=info method=GET path="/assets/application-62eb6ea61bd3bf9a7bd0671debada7702c7e73c172d3907e12be4f215b3f6f26.js" host=trisali.herokuapp.com request_id=e1e39f38-54aa-4a0a-a373-3ac8fedb1dfb fwd="79.228.15.18" dyno=web.1 connect=1ms service=4ms status=304 bytes=133
    2015-08-27T14:27:30.817473+00:00 heroku[router]: at=info method=GET path="/assets/logo-8ea26d6812f596f8039a97192a2b29d8ffeaa5be74be171fbe4b1ec9714619dd.png" host=trisali.herokuapp.com request_id=3c77f092-1cd1-4f46-839e-480c9f388079 fwd="79.228.15.18" dyno=web.1 connect=1ms service=10ms status=304 bytes=133
    2015-08-27T14:27:30.875613+00:00 heroku[router]: at=info method=GET path="/assets/thumb/avatar-fc2d14b6d5eed0015eb052d6e0bf0689cde252a4a7b2ba836d201c91365dd660.png" host=trisali.herokuapp.com request_id=b043d635-d741-4b9b-b765-4d0b4dcda8a4 fwd="79.228.15.18" dyno=web.1 connect=1ms service=7ms status=304 bytes=133
    2015-08-27T14:27:31.005440+00:00 heroku[router]: at=info method=GET path="/assets/ubuntu-light-927d0f3de91ec09c04bd5d432bb2575ecf619c819e4e035f235cf983319406ac.ttf" host=trisali.herokuapp.com request_id=2e028a06-52e1-4ff0-8aed-e6e089010ad3 fwd="79.228.15.18" dyno=web.1 connect=1ms service=42ms status=304 bytes=133
    2015-08-27T14:27:30.989872+00:00 heroku[router]: at=info method=GET path="/assets/honeyscript-light-c24ea12f7512d6a9407290d7e4a7ad0f4674bc419689d34d958b0f298b04710d.ttf" host=trisali.herokuapp.com request_id=d9a4fb49-2df8-4588-b4cf-a3ee21193c47 fwd="79.228.15.18" dyno=web.1 connect=1ms service=40ms status=304 bytes=133
    2015-08-27T14:27:31.101411+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=trisali.herokuapp.com request_id=faeccc93-48e9-41c4-937d-ecc78859bfdd fwd="79.228.15.18" dyno=web.1 connect=1ms service=7ms status=200 bytes=228
    2015-08-27T14:27:31.014883+00:00 heroku[router]: at=info method=GET path="/assets/florence-regular-6d0356416d75b142795ef23b178e5ddd64d26354fbed4710b14683db66432d87.otf" host=trisali.herokuapp.com request_id=6d737c83-8865-40ef-99ed-9eefa369abe1 fwd="79.228.15.18" dyno=web.1 connect=1ms service=45ms status=304 bytes=133
    2015-08-27T14:27:33.023611+00:00 app[web.1]: Started GET "/profiles/1-ralphathamburg/edit" for 79.228.15.18 at 2015-08-27 14:27:33 +0000
    2015-08-27T14:27:33.064803+00:00 app[web.1]:   User Load (17.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    2015-08-27T14:27:33.086375+00:00 app[web.1]:   Rendered profiles/_form.html.haml (8.4ms)
    2015-08-27T14:27:33.086434+00:00 app[web.1]:   Rendered profiles/edit.html.haml within layouts/application (13.3ms)
    2015-08-27T14:27:33.086667+00:00 app[web.1]: Completed 500 Internal Server Error in 59ms (ActiveRecord: 35.7ms)
    2015-08-27T14:27:33.174698+00:00 app[web.1]: Processing by ProfilesController#edit as HTML
    2015-08-27T14:27:33.174709+00:00 app[web.1]:   Parameters: {"id"=>"1-ralphathamburg"}
    2015-08-27T14:27:33.179791+00:00 app[web.1]:   Profile Load (4.1ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:27:33.197770+00:00 app[web.1]:   User Load (3.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:27:33.027147+00:00 app[web.1]: Processing by ProfilesController#edit as HTML
    2015-08-27T14:27:33.044420+00:00 app[web.1]:   Profile Load (16.2ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:27:33.027197+00:00 app[web.1]:   Parameters: {"id"=>"1-ralphathamburg"}
    2015-08-27T14:27:33.071420+00:00 app[web.1]:   User Load (1.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:27:33.087985+00:00 app[web.1]: 
    2015-08-27T14:27:33.087987+00:00 app[web.1]: ActionView::Template::Error (wrong number of arguments (4 for 0)):
    2015-08-27T14:27:33.087989+00:00 app[web.1]:     40:     %br/
    2015-08-27T14:27:33.087990+00:00 app[web.1]:     41:     
    2015-08-27T14:27:33.087991+00:00 app[web.1]:     42:     = t('.country')
    2015-08-27T14:27:33.087992+00:00 app[web.1]:     43:     = f.country_select :country_code, priority_countries: ["DE", "FR", "GB", "US"]
    2015-08-27T14:27:33.087994+00:00 app[web.1]:     44:     %br/
    2015-08-27T14:27:33.087995+00:00 app[web.1]:     45:     
    2015-08-27T14:27:33.087996+00:00 app[web.1]:     46:     = t('.avatar')
    2015-08-27T14:27:33.088000+00:00 app[web.1]:   app/views/profiles/edit.html.haml:6:in `_app_views_profiles_edit_html_haml___4198635066642818819_69926429943000'
    2015-08-27T14:27:33.087999+00:00 app[web.1]:   app/views/profiles/_form.html.haml:1:in `_app_views_profiles__form_html_haml___4095212724086949286_69926430019760'
    2015-08-27T14:27:33.087997+00:00 app[web.1]:   app/views/profiles/_form.html.haml:43:in `block in _app_views_profiles__form_html_haml___4095212724086949286_69926430019760'
    2015-08-27T14:27:33.088002+00:00 app[web.1]: 
    2015-08-27T14:27:33.088001+00:00 app[web.1]: 
    2015-08-27T14:27:33.193404+00:00 app[web.1]:   User Load (3.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    2015-08-27T14:27:33.167295+00:00 app[web.1]: Started GET "/profiles/1-ralphathamburg/edit" for 79.228.15.18 at 2015-08-27 14:27:33 +0000
    2015-08-27T14:27:33.089818+00:00 heroku[router]: at=info method=GET path="/profiles/1-ralphathamburg/edit" host=trisali.herokuapp.com request_id=ca8a50b1-d648-458a-8700-831a140c2aeb fwd="79.228.15.18" dyno=web.1 connect=1ms service=86ms status=500 bytes=1754
    2015-08-27T14:27:33.323672+00:00 app[web.1]:   Rendered profiles/_form.html.haml (117.6ms)
    2015-08-27T14:27:33.323708+00:00 app[web.1]:   Rendered profiles/edit.html.haml within layouts/application (124.5ms)
    2015-08-27T14:27:33.323970+00:00 app[web.1]: Completed 500 Internal Server Error in 149ms (ActiveRecord: 10.6ms)
    2015-08-27T14:27:33.341112+00:00 app[web.1]: 
    2015-08-27T14:27:33.341119+00:00 app[web.1]: ActionView::Template::Error (wrong number of arguments (4 for 0)):
    2015-08-27T14:27:33.341121+00:00 app[web.1]:     40:     %br/
    2015-08-27T14:27:33.341122+00:00 app[web.1]:     41:     
    2015-08-27T14:27:33.341124+00:00 app[web.1]:     42:     = t('.country')
    2015-08-27T14:27:33.341127+00:00 app[web.1]:     44:     %br/
    2015-08-27T14:27:33.341126+00:00 app[web.1]:     43:     = f.country_select :country_code, priority_countries: ["DE", "FR", "GB", "US"]
    2015-08-27T14:27:33.341128+00:00 app[web.1]:     45:     
    2015-08-27T14:27:33.341130+00:00 app[web.1]:     46:     = t('.avatar')
    2015-08-27T14:27:33.341132+00:00 app[web.1]:   app/views/profiles/_form.html.haml:43:in `block in _app_views_profiles__form_html_haml___4095212724086949286_69926430615040'
    2015-08-27T14:27:33.341133+00:00 app[web.1]:   app/views/profiles/_form.html.haml:1:in `_app_views_profiles__form_html_haml___4095212724086949286_69926430615040'
    2015-08-27T14:27:33.341135+00:00 app[web.1]:   app/views/profiles/edit.html.haml:6:in `_app_views_profiles_edit_html_haml___4198635066642818819_69926430562400'
    2015-08-27T14:27:33.341137+00:00 app[web.1]: 
    2015-08-27T14:27:33.341138+00:00 app[web.1]: 
    2015-08-27T14:27:33.339069+00:00 heroku[router]: at=info method=GET path="/profiles/1-ralphathamburg/edit" host=trisali.herokuapp.com request_id=01199b34-28e0-47ae-8490-cb4a56b73a0e fwd="79.228.15.18" dyno=web.1 connect=2ms service=180ms status=500 bytes=1754
    iMac:trisali ralph$ heroku logs
    2015-08-27T14:30:38.758256+00:00 app[web.1]: 	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:162:in `start'
    2015-08-27T14:30:38.758391+00:00 app[web.1]: [2015-08-27 14:30:38] INFO  WEBrick::HTTPServer#start done.
    2015-08-27T14:30:38.758258+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
    2015-08-27T14:30:38.758465+00:00 app[web.1]: => Booting WEBrick
    2015-08-27T14:30:38.758263+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
    2015-08-27T14:30:38.758467+00:00 app[web.1]: => Rails 4.2.3 application starting in production on http://0.0.0.0:5257
    2015-08-27T14:30:38.758264+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
    2015-08-27T14:30:38.758469+00:00 app[web.1]: => Run `rails server -h` for more startup options
    2015-08-27T14:30:39.630864+00:00 heroku[web.1]: Process exited with status 143
    2015-08-27T14:30:51.891857+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 7319 -e production`
    2015-08-27T14:30:53.408390+00:00 heroku[worker.1]: Starting process with command `bundle exec rake jobs:work`
    2015-08-27T14:30:54.001840+00:00 heroku[worker.1]: State changed from starting to up
    2015-08-27T14:30:58.474870+00:00 app[worker.1]: rake aborted!
    2015-08-27T14:30:58.475038+00:00 app[worker.1]: 
    2015-08-27T14:30:58.474902+00:00 app[worker.1]: Don't know how to build task 'jobs:work'
    2015-08-27T14:30:58.475059+00:00 app[worker.1]: (See full trace by running task with --trace)
    2015-08-27T14:31:00.004476+00:00 heroku[worker.1]: Process exited with status 1
    2015-08-27T14:31:00.016282+00:00 heroku[worker.1]: State changed from up to crashed
    2015-08-27T14:31:00.970820+00:00 heroku[web.1]: State changed from starting to up
    2015-08-27T14:31:00.557247+00:00 app[web.1]: [2015-08-27 14:31:00] INFO  WEBrick 1.3.1
    2015-08-27T14:31:00.557279+00:00 app[web.1]: [2015-08-27 14:31:00] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
    2015-08-27T14:31:00.557635+00:00 app[web.1]: [2015-08-27 14:31:00] INFO  WEBrick::HTTPServer#start: pid=3 port=7319
    2015-08-27T14:31:06.295167+00:00 heroku[router]: at=info method=GET path="/" host=trisali.herokuapp.com request_id=68485716-212b-4315-bcaf-d7cbd10144b2 fwd="79.228.15.18" dyno=web.1 connect=0ms service=286ms status=200 bytes=4742
    2015-08-27T14:31:06.017186+00:00 app[web.1]: => Run `rails server -h` for more startup options
    2015-08-27T14:31:06.017178+00:00 app[web.1]: => Booting WEBrick
    2015-08-27T14:31:06.017189+00:00 app[web.1]: Started GET "/" for 79.228.15.18 at 2015-08-27 14:31:06 +0000
    2015-08-27T14:31:06.017184+00:00 app[web.1]: => Rails 4.2.3 application starting in production on http://0.0.0.0:7319
    2015-08-27T14:31:06.130478+00:00 app[web.1]:   Mood Load (1.5ms)  SELECT "moods".* FROM "moods"
    2015-08-27T14:31:06.158511+00:00 app[web.1]:   Profile Load (1.4ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = $1 LIMIT 1  [["user_id", 1]]
    2015-08-27T14:31:06.017187+00:00 app[web.1]: => Ctrl-C to shutdown server
    2015-08-27T14:31:06.091999+00:00 app[web.1]: Processing by PagesController#landing as HTML
    2015-08-27T14:31:06.124365+00:00 app[web.1]:   User Load (2.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    2015-08-27T14:31:06.135201+00:00 app[web.1]:   Rendered pages/landing.html.haml within layouts/application (30.2ms)
    2015-08-27T14:31:06.290883+00:00 app[web.1]:   Rendered layouts/_header.html.haml (149.3ms)
    2015-08-27T14:31:06.295363+00:00 app[web.1]: Completed 200 OK in 203ms (Views: 183.8ms | ActiveRecord: 9.8ms)
    2015-08-27T14:31:06.294926+00:00 app[web.1]:   Rendered layouts/_footer.html.haml (2.9ms)
    2015-08-27T14:31:06.877132+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=trisali.herokuapp.com request_id=488689ca-561d-4472-9037-1722096c0ad0 fwd="79.228.15.18" dyno=web.1 connect=2ms service=15ms status=304 bytes=133
    2015-08-27T14:31:09.915277+00:00 app[web.1]:   User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:31:10.070990+00:00 app[web.1]:   User Load (1.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    2015-08-27T14:31:10.091828+00:00 app[web.1]:   Rendered layouts/_header.html.haml (11.4ms)
    2015-08-27T14:31:09.896502+00:00 app[web.1]: Started GET "/profiles/1-ralphathamburg" for 79.228.15.18 at 2015-08-27 14:31:09 +0000
    2015-08-27T14:31:10.078148+00:00 app[web.1]:   Experience Load (1.4ms)  SELECT "experiences".* FROM "experiences" WHERE "experiences"."user_id" = $1  [["user_id", 1]]
    2015-08-27T14:31:09.903042+00:00 app[web.1]:   Parameters: {"id"=>"1-ralphathamburg"}
    2015-08-27T14:31:09.903033+00:00 app[web.1]: Processing by ProfilesController#show as HTML
    2015-08-27T14:31:09.922145+00:00 app[web.1]:   ActsAsVotable::Vote Load (1.5ms)  SELECT "votes".* FROM "votes" WHERE "votes"."vote_flag" = $1 AND "votes"."voter_id" = $2 AND "votes"."voter_type" = $3  [["vote_flag", "t"], ["voter_id", 1], ["voter_type", "User"]]
    2015-08-27T14:31:10.078517+00:00 app[web.1]:   Rendered experiences/_experience.html.haml (0.0ms)
    2015-08-27T14:31:09.908604+00:00 app[web.1]:   Profile Load (1.4ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:31:10.078627+00:00 app[web.1]:   Rendered profiles/show.html.haml within layouts/application (147.5ms)
    2015-08-27T14:31:10.101074+00:00 app[web.1]:   Rendered layouts/_footer.html.haml (6.1ms)
    2015-08-27T14:31:10.090281+00:00 app[web.1]:   Profile Load (4.9ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = $1 LIMIT 1  [["user_id", 1]]
    2015-08-27T14:31:10.073529+00:00 app[web.1]:   Rendered experiences/_experience.html.haml (0.0ms)
    2015-08-27T14:31:10.101079+00:00 app[web.1]: Completed 200 OK in 196ms (Views: 163.1ms | ActiveRecord: 18.1ms)
    2015-08-27T14:31:10.113050+00:00 heroku[router]: at=info method=GET path="/profiles/1-ralphathamburg" host=trisali.herokuapp.com request_id=d1d3790e-e76a-4f94-93bd-0028015452f4 fwd="79.228.15.18" dyno=web.1 connect=0ms service=221ms status=200 bytes=4189
    2015-08-27T14:31:12.715635+00:00 app[web.1]: Started GET "/profiles/1-ralphathamburg/edit" for 79.228.15.18 at 2015-08-27 14:31:12 +0000
    2015-08-27T14:31:12.729032+00:00 app[web.1]:   User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    2015-08-27T14:31:12.760298+00:00 app[web.1]: Completed 500 Internal Server Error in 40ms (ActiveRecord: 6.0ms)
    2015-08-27T14:31:12.831400+00:00 app[web.1]: Processing by ProfilesController#edit as HTML
    2015-08-27T14:31:12.759740+00:00 app[web.1]:   Rendered profiles/_form.html.haml (22.8ms)
    2015-08-27T14:31:12.831518+00:00 app[web.1]:   Parameters: {"id"=>"1-ralphathamburg"}
    2015-08-27T14:31:12.835200+00:00 app[web.1]:   Profile Load (1.5ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:31:12.844734+00:00 app[web.1]:   User Load (1.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:31:12.882000+00:00 app[web.1]: 
    2015-08-27T14:31:12.882003+00:00 app[web.1]: ActionView::Template::Error (wrong number of arguments (4 for 0)):
    2015-08-27T14:31:12.882005+00:00 app[web.1]:     40:     %br/
    2015-08-27T14:31:12.882006+00:00 app[web.1]:     41:     
    2015-08-27T14:31:12.882008+00:00 app[web.1]:     42:     = t('.country')
    2015-08-27T14:31:12.882017+00:00 app[web.1]:   app/views/profiles/_form.html.haml:1:in `_app_views_profiles__form_html_haml__3452334975995466329_70067594082940'
    2015-08-27T14:31:12.882010+00:00 app[web.1]:     43:     = f.country_select :country_code, priority_countries: ["DE", "FR", "GB", "US"]
    2015-08-27T14:31:12.882011+00:00 app[web.1]:     44:     %br/
    2015-08-27T14:31:12.882012+00:00 app[web.1]:     45:     
    2015-08-27T14:31:12.882014+00:00 app[web.1]:     46:     = t('.avatar')
    2015-08-27T14:31:12.882015+00:00 app[web.1]:   app/views/profiles/_form.html.haml:43:in `block in _app_views_profiles__form_html_haml__3452334975995466329_70067594082940'
    2015-08-27T14:31:12.882018+00:00 app[web.1]:   app/views/profiles/edit.html.haml:6:in `_app_views_profiles_edit_html_haml___3094411535297841784_70067594130400'
    2015-08-27T14:31:12.882020+00:00 app[web.1]: 
    2015-08-27T14:31:12.882021+00:00 app[web.1]: 
    2015-08-27T14:31:12.720433+00:00 app[web.1]: Processing by ProfilesController#edit as HTML
    2015-08-27T14:31:12.761857+00:00 app[web.1]: 
    2015-08-27T14:31:12.720511+00:00 app[web.1]:   Parameters: {"id"=>"1-ralphathamburg"}
    2015-08-27T14:31:12.759934+00:00 app[web.1]:   Rendered profiles/edit.html.haml within layouts/application (26.2ms)
    2015-08-27T14:31:12.761860+00:00 app[web.1]: ActionView::Template::Error (wrong number of arguments (4 for 0)):
    2015-08-27T14:31:12.761862+00:00 app[web.1]:     40:     %br/
    2015-08-27T14:31:12.725816+00:00 app[web.1]:   Profile Load (3.4ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:31:12.731737+00:00 app[web.1]:   User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
    2015-08-27T14:31:12.761865+00:00 app[web.1]:     42:     = t('.country')
    2015-08-27T14:31:12.761870+00:00 app[web.1]:     45:     
    2015-08-27T14:31:12.761864+00:00 app[web.1]:     41:     
    2015-08-27T14:31:12.761871+00:00 app[web.1]:     46:     = t('.avatar')
    2015-08-27T14:31:12.761874+00:00 app[web.1]:   app/views/profiles/_form.html.haml:1:in `_app_views_profiles__form_html_haml__3452334975995466329_70067603402560'
    2015-08-27T14:31:12.761867+00:00 app[web.1]:     43:     = f.country_select :country_code, priority_countries: ["DE", "FR", "GB", "US"]
    2015-08-27T14:31:12.761868+00:00 app[web.1]:     44:     %br/
    2015-08-27T14:31:12.761876+00:00 app[web.1]:   app/views/profiles/edit.html.haml:6:in `_app_views_profiles_edit_html_haml___3094411535297841784_70067603383520'
    2015-08-27T14:31:12.824955+00:00 app[web.1]: Started GET "/profiles/1-ralphathamburg/edit" for 79.228.15.18 at 2015-08-27 14:31:12 +0000
    2015-08-27T14:31:12.842542+00:00 app[web.1]:   User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
    2015-08-27T14:31:12.761873+00:00 app[web.1]:   app/views/profiles/_form.html.haml:43:in `block in _app_views_profiles__form_html_haml__3452334975995466329_70067603402560'
    2015-08-27T14:31:12.879581+00:00 app[web.1]: Completed 500 Internal Server Error in 48ms (ActiveRecord: 4.3ms)
    2015-08-27T14:31:12.761877+00:00 app[web.1]: 
    2015-08-27T14:31:12.761878+00:00 app[web.1]: 
    2015-08-27T14:31:12.879290+00:00 app[web.1]:   Rendered profiles/_form.html.haml (25.1ms)
    2015-08-27T14:31:12.879365+00:00 app[web.1]:   Rendered profiles/edit.html.haml within layouts/application (33.8ms)
    2015-08-27T14:31:12.761172+00:00 heroku[router]: at=info method=GET path="/profiles/1-ralphathamburg/edit" host=trisali.herokuapp.com request_id=d8e23f0d-0285-41aa-948c-494e1e069352 fwd="79.228.15.18" dyno=web.1 connect=0ms service=52ms status=500 bytes=1754
    2015-08-27T14:31:12.881072+00:00 heroku[router]: at=info method=GET path="/profiles/1-ralphathamburg/edit" host=trisali.herokuapp.com request_id=e8a4f65b-e865-4040-be81-b2ae93a97456 fwd="79.228.15.18" dyno=web.1 connect=0ms service=65ms status=500 bytes=1754

**Comment by scudco** [comment]
hmm, I was thinking the full stack trace with the line in country_select that would be failing, but I guess on  heroku you can't see that.

**Comment by RalphAtHamburg** [comment]
Setting RAILS_ENV to development on:

Heroku -> Apps -> Settings -> Config Variables

brings it to run on heroku. It must be something in the environment rb files

**Comment by scudco** [comment]
Cleaning up issues. Feel free to re-open if you have more information on this.
